### PR TITLE
Updated package meta and contribution for 1.3.0

### PR DESCRIPTION
**Pull request by tonybaloney**
- patch no longer required as referring PR was merged and updates are included in this release
- version updated 1.3.0
- updated hash
- updated list of maintainers to include me

### CODE REVIEW

**Comment by tonybaloney** [comment]
cc @nmadhok @danielfrg

**Comment by danielfrg** [comment]
Thanks for the contribution. I have restarted the failed builds.

**Comment by danielfrg** [comment]
This keeps failing for some reason, not exactly sure why.

**Comment by danielfrg** [comment]
I am sorry this took for ever but I made this changes on #8 and you are now a maintainer on the conda pkg.

**Pull request closed without merging**
